// <auto-generated />
using System;
using CrudWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudWeb.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CrudWeb.Models.Conteiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Categoria");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cliente");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Numero");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Conteiner");
                });

            modelBuilder.Entity("CrudWeb.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Conteiner_Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Conteiner_Id");

                    b.Property<DateTime>("DH_Finais")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DH_Finais");

                    b.Property<DateTime>("DH_Iniciais")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DH_Inicais");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Procedimento");

                    b.HasKey("Id");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("CrudWeb.Models.Relato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cliente");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Procedimento");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Relato");
                });
#pragma warning restore 612, 618
        }
    }
}
